### PR TITLE
Sentry environment, job config `interval`, fix shutdown, minor improvements

### PR DESCRIPTION
**Pull request by droserasprout**

### CODE REVIEW

**Comment by droserasprout** [comment]
[aiohttp.ClientSession() wants to be called inside a coroutine](https://trello.com/c/lDDxW2ph/156-aiohttpclientsession-wants-to-be-called-inside-a-coroutine)

**Comment by droserasprout** [comment]
[Global decimal precision = max across all decimal fields in db models](https://trello.com/c/NXifeAJA/173-global-decimal-precision-max-across-all-decimal-fields-in-db-models)

**Comment by droserasprout** [comment]
[Graceful shutdown Ctrl+C](https://trello.com/c/Kaj6HqlP/161-graceful-shutdown)

**Comment by droserasprout** [comment]
[Handle "Server disconnected"](https://trello.com/c/Uc3PCAfa/158-handle-server-disconnected)

**Comment by droserasprout** [comment]
[Handle "Client connector error"](https://trello.com/c/BrFxdLKa/160-handle-client-connector-error)

**Review by m-kus — APPROVED** [review]

**Pull request merged**
