### PR TITLE
Hasura config and table customisation improvements

### PR DESCRIPTION
**Pull request by 852Kerfunkle**
Heya,

I added the `add_source` option to the hasura config to be able to add a db under a custom source name instead up using the default. Please note I opted to mostly go with the default settings (except for use_prepared_statements).

I also fixed issue #306. That could maybe be improved (didn't have time to look into the introspection stuff), but it works.

### CODE REVIEW

**Comment by droserasprout** [comment]
Sorry, I have to postpone merging this for another release.

**Comment by droserasprout** [comment]
Hey, @852Kerfunkle! Sorry, it took me so long to review your PR. You had not ticked "Allow edits from maintainers" while creating it. Please, apply the attached patch, and I'm ready to merge this code according to milestones.

[review.patch.txt](https://github.com/dipdup-net/dipdup-py/files/8778329/review.patch.txt)

**Comment by 852Kerfunkle** [comment]
Thank you very much! I will keep that in mind.

**Review by droserasprout — APPROVED** [review]

**Comment by droserasprout** [comment]
@852Kerfunkle, can you rebase this branch against master once again?

**Comment by 852Kerfunkle** [comment]
Sure thing, done.

**Pull request merged**
