### PR TITLE
Hooks, typed callbacks, more builtin tables, no more tempstates

### PR DESCRIPTION
**Pull request by droserasprout**
Improvements:

* New entity: hook. User-defined callback with arbitrary code. Same as handler but not linked to any index. Called either from `ctx.fire_hook` (from hadlers or by DupDup) or by scheduler (`jobs` config section). Optionally typed with `args`. Jobs are now schedules for hooks.

```
hooks:
  a:
    callback: a
    atomic: True
    args:
     foo: int
     bar: str

jobs:
  a_leet:
    hook: a
    interval: 1337
    args:
      foo: 1337
      bar: "1337"
```

* SQL hooks. `hooks/callback.sql` directory next to `hooks/callback.py`. Both Python and SQL hooks are always fired (but not nescessary non-empty). Executed by `CallbackManager`.
* Built-in hooks defined declaratively in config.

* Unified codegen based on a single template for all callbacks. Config section must implement `CallbackMixin`.
* Unified callbacks processing in `CallbackManager`. Optional dynamic type-checking of arguments (basic types and dotted notations, skipped for handlers).
* All above finally apply to big_map indexes, debt closed.
* Massive refactoring of `dipdup.config` module. Easier to understand stages of complex config initialization flow.
* Callback-specific context classes removed. Callbacks receive either `HandlerContext` or `HookContext`. Required context created in base context.

* Matching Websocket data with cached head block.
* Bunch of internal models:
    * `Schema`: just hash
    * `Index`: status, template, template values, full config
    * `Head`: last Websocket connection status
    * `Contract`: hack to keep dynamically spawned contracts after restart (ignored if presented in config)

* No more "temporary states"!
    1. Indexes from config: just verify hash
    2. Indexes from template: recreate from config template, check hash
    3. Indexes with template missing: reindex
    4. Indexes without template not in config: ignore (must be just commented out)

See edge cases in TODO.

* Datasource now maintains linked `models.Head`. More on int.models below.
* Completely rewritten DipDup boot sequence. Main entrypoint splitted to _set_up_smth methods using stack and task set.

TODO:

* Reindex if `on_rollback` hook is not implemented
* Fix `ParentMixin` generic
* Fix formatted loggers missing context due to init in base context
* Set `ONESHOT` status on complete
* Context reused between job runs
* Factory level updated, config not reloaded, indexer dies -> invalid state
* Project migration: move SQL scripts, remove default handlers
* Check migration on demos
* Spec and major version bump
* `hooks: List[HookConfig]`? Now `name` must be equal to `callback`.

### CODE REVIEW

**Comment by droserasprout** [comment]
[Store block datetime in dipdup_state](https://trello.com/c/gE9lRvDT/221-store-block-datetime-in-dipdupstate)

**Comment by droserasprout** [comment]
[Index level and sync level in DipDupState.](https://trello.com/c/2hJD2Hap/208-index-level-and-sync-level-in-dipdupstate)

**Comment by droserasprout** [comment]
[Save spawned indexes, drop `stateless` option](https://trello.com/c/JDvnBS5X/125-save-spawned-indexes-drop-stateless-option)

**Comment by droserasprout** [comment]
[Typed index settings (template values)](https://trello.com/c/ss3sStzm/185-typed-index-settings-template-values)

**Comment by droserasprout** [comment]
[quipuswap_fa2_guts: Config hash mismatch (config has been changed), reindexing](https://trello.com/c/UUPm243x/234-quipuswapfa2guts-config-hash-mismatch-config-has-been-changed-reindexing)

**Comment by droserasprout** [comment]
[Epic 3.0.0 branch](https://trello.com/c/7OIn7JF5/246-epic-300-branch)

**Comment by droserasprout** [comment]
[Graceful shutdown is broken](https://trello.com/c/baXFS2Ka/190-graceful-shutdown-is-broken)

**Comment by droserasprout** [comment]
[camelCase table columns break Hasura](https://trello.com/c/BLCIA6Kh/253-camelcase-table-columns-break-hasura)

**Review by m-kus — APPROVED** [review]

**Pull request merged**
